### ISSUE TITLE
Problems with running on the canvas kit renderer

### ISSUE THREAD

**Issue by DaveShuckerow** [flutter/devtools#1354]
```
flutter run -d chrome --dart-define=FLUTTER_WEB_USE_SKIA=true --release
```

Runs DevTools with a few noticeable issues:

* [ ] Fonts look off:
Canvas Kit: 
![image](https://user-images.githubusercontent.com/14947366/69107545-9864cf80-0a26-11ea-86de-0a0abe34ee9c.png)
Normal:
![image](https://user-images.githubusercontent.com/14947366/69107561-9f8bdd80-0a26-11ea-8a0a-2c2967b20c03.png)

* [x] Platform Views not showing up:
![image](https://user-images.githubusercontent.com/14947366/69107397-11175c00-0a26-11ea-9260-386a428da646.png)

* [x] Charts are not painting right:
![image](https://user-images.githubusercontent.com/14947366/69107406-170d3d00-0a26-11ea-8b6c-8de80df94b57.png)

* [ ] CanvasKit sometimes runs out of resources and crashes.
<img width="574" alt="Screen Shot 2020-03-11 at 4 58 50 PM" src="https://user-images.githubusercontent.com/1226812/76474750-d01ecb00-63b9-11ea-9fc3-dfd288229b0d.png">
https://github.com/flutter/flutter/issues/52447

**Comment by DaveShuckerow** [comment]
I get the platform view issue in regular release mode builds too, not just canvas kit builds.

**Comment by jacob314** [comment]
Are there bugs on package:flutter filed for these issues?
We can live with the font issue for now but the other issues are launch blockers.

**Comment by jacob314** [comment]
The platform view issue doesn't block shipping as we should be able to ship the debugger page without depending on platform views. All other issues are blocking but may have already been fixed in CanvasKit.

**Comment by kenzieschmoll** [comment]
Is the only thing remaining here "CanvasKit sometimes runs out of resources and crashes."? Are we still seeing this issue?

**Comment by kenzieschmoll** [comment]
closing this as canvas kit issues are being tracked elsewhere
