### ISSUE TITLE
Navigating to Memory page on Desktop is broken

### ISSUE THREAD

**Issue by kenzieschmoll** [flutter/devtools#1588]
Repro steps:
- Launch DevTools.
- Navigate to memory or perf page - observe DevTools lock up

I am going to try to bisect to find culprit CL.

**Comment by kenzieschmoll** [comment]
It is possible that this is a Flutter issue. Saw this bug against flutter version Flutter 1.14.7-pre.45.

**Comment by kenzieschmoll** [comment]
Confirmed this is in fact a DevTools issue. This is the culprit CL https://github.com/flutter/devtools/commit/7189969fddab558a1023fd974c97a57fdd38f5a2 @terrylucas

**Comment by terrylucas** [comment]
Is this DevTools Flutter, Web or HTML?  Flutter works I'll try the others.

**Comment by terrylucas** [comment]
Looks like it in Flutter Web there's an unimplemented canvas feature.

**Comment by terrylucas** [comment]
Please confirm that its Flutter Web that's causing your failure.

**Comment by terrylucas** [comment]
Fixed with PR https://github.com/flutter/devtools/pull/1593.

**Comment by kenzieschmoll** [comment]
Pulled in your change, and I am still seeing this on Flutter Desktop.
![navigation_broken](https://user-images.githubusercontent.com/43759233/73552270-c8ecc080-43fc-11ea-907f-dc3d0a5317d1.gif)

**Comment by kenzieschmoll** [comment]
I think this is a big enough bug to be a release blocker, especially if we are including details of the new memory features in the release notes. If it can't be fixed before releasing today, maybe we should roll back the culprit CL.

**Comment by terrylucas** [comment]
I can not repro this at all on Flutter Desktop Mac/Linux debug or release
(Mac only).  What application are you running?  I'm on tip of Flutter,
flutter update-packages and flutter clean.  Do you have any output either
in output from devtools run the flutter run of the application being
debugged?

**Comment by kenzieschmoll** [comment]
I am able to navigate to the memory page on flutter web, but there is no data:
<img width="1648" alt="Screen Shot 2020-01-31 at 7 50 37 AM" src="https://user-images.githubusercontent.com/43759233/73553227-6b597380-43fe-11ea-9f75-ad146c81e3c1.png">
This is in the console: 
```
════════ Exception caught by rendering library ═════════════════════════════════════════════════════
The following UnsupportedError was thrown during paint():
Unsupported operation: NaN

The relevant error-causing widget was: 
  CustomPaint org-dartlang-app:///packages/mp_chart/mp/chart/chart.dart:110:31
When the exception was thrown, this was the stack: 
package:dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 196:49  throw_
package:dart-sdk/lib/_internal/js_dev_runtime/private/js_number.dart 82:5             toInt]
package:dart-sdk/lib/_internal/js_dev_runtime/private/js_number.dart 92:34            floor]
package:mp_chart/mp/core/render/axis_renderer.dart 197:42                             computeAxisValues
package:mp_chart/mp/core/render/axis_renderer.dart 127:5                              computeAxis
...
The following RenderObject was being processed when the exception was fired: RenderCustomPaint#4f0bd
...  parentData: <none> (can use size)
...  constraints: BoxConstraints(w=1616.0, h=182.0)
...  size: Size(1616.0, 182.0)
RenderObject: RenderCustomPaint#4f0bd
  parentData: <none> (can use size)
  constraints: BoxConstraints(w=1616.0, h=182.0)
  size: Size(1616.0, 182.0)
════════════════════════════════════════════════════════════════════════════════════════════════════
```

In html devtools connected to the same app, there is data:
<img width="1656" alt="Screen Shot 2020-01-31 at 7 51 29 AM" src="https://user-images.githubusercontent.com/43759233/73553269-82986100-43fe-11ea-8c1d-feda75e1cd27.png">

**Comment by kenzieschmoll** [comment]
I am on tip of trunk flutter. Have ran `flutter update-packages` and `flutter clean`. Still seeing issue.

**Comment by terrylucas** [comment]
Okay I've updated to latest tip of Flutter e.g.,

```
> flutter --version
Flutter 1.14.7-pre.63 • channel master • git@github.com:terrylucas/flutter.git
Framework • revision effc019054 (19 minutes ago) • 2020-02-01 00:20:04 +0800
Engine • revision 804dca62a1
Tools • Dart 2.8.0 (build 2.8.0-dev.6.0 162d6c5634)
```

Deleted build flutter tool snapshot (shouldn't be necessary but this forces a rebuild of Flutter tool).
`> rm $FLUTTER_HOME/bin/cache/flutter_tools.*`

then first time flutter is run e.g., flutter --version you should see:
`Building flutter tool...`

Then

`> flutter update-packages`

cd to the examples/flutter_gallery
`> flutter clean`

Checked that flutter is same for the two shells:
- application I'm running flutter_gallery
- DevTools from MacOS Desktop run

```
> which flutter
/Users/terry/flutter-engine-git/flutter/bin/flutter 
```
both of mine point to same directory

The Android emulator I'm running:

Pixel_XL_API_28     • Pixel XL API 28 • Google • android

Everything works...

**Comment by kenzieschmoll** [comment]
Tested on linux and everything is WAI. Perhaps something is corrupted in my local setup on mac.

**Comment by kenzieschmoll** [comment]
Strange - the issue only occurs when Flutter DevTools is launched from IntelliJ. I can repro the issue every time when launching from IntelliJ but not when launching via command line `flutter run -d macos`
@devoncarew @jacob314  any ideas why these two launch avenues would produce different results?

**Comment by jacob314** [comment]
I would look at the Dart VM flags from the info screen to see if anything is different. Are any exceptions thrown? Are any errors thrown when running from intellij?

**Comment by jacob314** [comment]
The other option is your intelliJ might be using a different version of package:flutter than you are using from the command line. I would doublecheck that first.

**Comment by kenzieschmoll** [comment]
Flutter version is the same in IntelliJ and CLI. No exceptions are thrown in IntelliJ when this happens. The desktop app just freezes and my mac starts to make the "working-too-hard" fan sound.

**Comment by kenzieschmoll** [comment]
I have no explanation as to why, but I'm not seeing the issue anymore... I guess we'll just mark this as resolved unless it happens again.

**Comment by kenzieschmoll** [comment]
Seeing this again @terrylucas

**Comment by kenzieschmoll** [comment]
@jacob314 just confirming that you fixed this issue. If so, let's close.

**Comment by terrylucas** [comment]
Has you seen this Kenzie, I think you use to see this too?

**Comment by kenzieschmoll** [comment]
I haven't seen this in a while, and IIRC, Jacob made a change that fixed this. Closing.

**Comment by kenzieschmoll** [comment]
@terrylucas I am seeing this again on MacOs.
