### ISSUE TITLE
Layout Explorer not visible/available when debugging flutter web apps

### ISSUE THREAD

**Issue by nickmeinhold** [flutter/devtools#2180]
Sorry if this is expected behaviour but I couldn't find it documented anywhere. 

Repro steps: 
- run devtools 
- create a new flutter project 
- `flutter run -d macOS` 
- paste the URL from running the app into devtools 

<img width="876" alt="Screen Shot 2020-07-14 at 4 22 30 pm" src="https://user-images.githubusercontent.com/1059276/87391645-7be95900-c5ee-11ea-9769-9ceed15dc17b.png">

- close the app 
- `flutter run -d chrome`
- paste the URL from running the app into devtools 

<img width="877" alt="Screen Shot 2020-07-14 at 4 23 59 pm" src="https://user-images.githubusercontent.com/1059276/87391715-98859100-c5ee-11ea-8eaf-d182d912e2b9.png">

<details>
<summary>flutter doctor -v</summary>

[✓] Flutter (Channel unknown, 1.20.0-7.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-AU)
    • Flutter version 1.20.0-7.0.pre at /Users/nick/Documents/SDKs/flutter
    • Framework revision cc1af3afb6 (6 days ago), 2020-07-08 10:19:36 -0700
    • Engine revision 0dc86cda19
    • Dart version 2.9.0 (build 2.9.0-20.0.dev 06cb010247)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nick/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome
      83.0.4103.116
</details>

**Comment by jacob314** [comment]
Unfortunately the layout explorer needs more advanced evaluation support that we are currently in the process of adding for flutter-web. As soon as the eval support is good enough, this functionality will be enabled for Flutter Web as well. For now, I'd encourage you to develop with flutter desktop and then deploy to flutter web. That will also give you hot reload for a faster development experience.

**Comment by wilpar** [comment]
Glad to have found this caveat.  Wish the videos that got me all excited mentioned this!

**Comment by annagrin** [comment]
This is fixed in https://github.com/flutter/devtools/issues/2832.

**Comment by nickmeinhold** [comment]
Awesome, thanks for all your great work!

**Comment by siva636** [comment]
The layout explored is still missing for me.
Flutter: 2.0.4 stable channel
Dart Code: V3.14.1

**Comment by annagrin** [comment]
@siva636 the fix is still only in master - in 2.2.0-10.1.pre and  2.2.0-10.0.pre. Thank for trying it out!
