### ISSUE TITLE
Network requests shows blank in v0.9.0

### ISSUE THREAD

**Issue by shashikantdurge** [flutter/devtools#2257]
Network tab shows no requests
![Screenshot 2020-08-10 at 7 23 16 PM](https://user-images.githubusercontent.com/20161204/89794377-99a1d380-db44-11ea-8b31-9a8f86f2859a.png)

**Comment by kenzieschmoll** [comment]
Are there any errors in the chrome console? How are you sending network requests from your application?

**Comment by shashikantdurge** [comment]
I also get this dialog when I stop recording 
![Screenshot 2020-08-10 at 8 33 36 PM](https://user-images.githubusercontent.com/20161204/89797645-ca840780-db48-11ea-9948-0ef05d1da9a6.png)

**Comment by shashikantdurge** [comment]
logs from chrome console
![Screenshot 2020-08-10 at 8 35 01 PM](https://user-images.githubusercontent.com/20161204/89797784-facba600-db48-11ea-96bd-7efd446e4375.png)

**Comment by shashikantdurge** [comment]
I'm sending the requests using package [dio](https://pub.dev/packages/dio)

**Comment by shashikantdurge** [comment]
![Screenshot 2020-08-11 at 10 41 40 AM](https://user-images.githubusercontent.com/20161204/89859705-41f47e00-dbbf-11ea-86bf-083a7973e96c.png)

Chrome console errors

**Comment by devoncarew** [comment]
Thanks for the report! That stack trace looks pretty actionable.

**Comment by b1acKr0se** [comment]
Has the fix gone live? I'm still experiencing this issue. If not, what's the plan for this?

**Comment by kenzieschmoll** [comment]
The fix has not gone live. It will go out with our next release. If we send out a dev release before then, I'll be sure to update this issue.

**Comment by kenzieschmoll** [comment]
I published 0.9.1-dev.3, which includes the fix for this bug. You can use this version of DevTools by running `flutter pub global activate devtools 0.9.1-dev.3`, followed by `flutter pub global run devtools`. This fix will also be included in the next stable release at the end of the month.

**Comment by b1acKr0se** [comment]
@kenzieschmoll Thank you for your hard work. It seems that this issue still persists in the dev version (0.9.1-dev.3), but there's no stack trace this time.

<img width="1439" alt="Screen Shot 2020-08-18 at 12 53 54" src="https://user-images.githubusercontent.com/8596158/90475643-0e32ce80-e152-11ea-9f7f-25eddeff455f.png">
