### ISSUE TITLE
Unable to inspect response bodies on Network page

### ISSUE THREAD

**Issue by gustavogamino** [flutter/devtools#2398]
As described at the [Flutter 1.22 announcement - Updated Network Page in DevTools](https://medium.com/flutter/announcing-flutter-1-22-44f146009e5f#10ac), we should be able to inspect network calls after getting the newest flutter version using `flutter upgrade`, but I'm not able to locate/use the feature.

I'm currently running devtools 0.9.2, so I tried to force the update to the latest release by running `pub global activate devtools 0.9.3` but it fails trying to resolve dependencies:
```shell
Because devtools >=0.9.3 depends on devtools_shared 0.9.3 which doesn't match any versions, devtools >=0.9.3 is forbidden.
So, because pub global activate depends on devtools 0.9.3, version solving failed.
pub finished with exit code 1
```
You can check the same error on pub.dev here https://pub.dev/documentation/devtools/0.9.3/log.txt

So what I tried instead was to clone this repo and build from `v0.9.3` tag and `master` branch. In both cases the build passes fine, but again the feature doesn't seem to be there. Every request on the Network page never completes, so no `Response` tab appears and `Header` sections are empty.

While running the app in debug mode one of the exceptions shown was this one:
```
Error: Assertion failed: file:///.../devtools/packages/devtools_app/lib/src/http/http_request_data.dart:62:16
requestEndEvent == null
is not true
    at Object.throw_ [as throw] (http://localhost:63874/dart_sdk.js:4333:11)
    at Object.assertFailed (http://localhost:63874/dart_sdk.js:4276:15)
    at Function.fromTimeline (http://localhost:63874/packages/devtools_app/src/ui/gtags.dart.lib.js:68892:48)
    at network_controller.NetworkController.new.processNetworkTrafficHelper
    (http://localhost:63874/packages/devtools_app/src/ui/gtags.dart.lib.js:69224:61)
    at network_controller.NetworkController.new.processNetworkTraffic
    (http://localhost:63874/packages/devtools_app/src/ui/gtags.dart.lib.js:69254:36)
    at network_service.NetworkService.new.refreshNetworkData
    (http://localhost:63874/packages/devtools_app/src/ui/gtags.dart.lib.js:68569:32)
    at refreshNetworkData.next (<anonymous>)
    at http://localhost:63874/dart_sdk.js:37669:33
    at _RootZone.runUnary (http://localhost:63874/dart_sdk.js:37523:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:63874/dart_sdk.js:32497:29)
    at handleValueCallback (http://localhost:63874/dart_sdk.js:33044:49)
    at Function._propagateToListeners (http://localhost:63874/dart_sdk.js:33082:17)
    at _Future.new.[_completeWithValue] (http://localhost:63874/dart_sdk.js:32925:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:63874/dart_sdk.js:32947:35)
    at Object._microtaskLoop (http://localhost:63874/dart_sdk.js:37784:13)
    at _startMicrotaskLoop (http://localhost:63874/dart_sdk.js:37790:13)
    at http://localhost:63874/dart_sdk.js:33299:9
```

Relevant information from `flutter doctor` 
```shell
[✓] Flutter (Channel stable, 1.22.0, on Mac OS X 10.15.6 19G2021)
    • Flutter version 1.22.0
    • Framework revision d408d302e2 (2 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0
```

Is this feature not ready yet, despite the announcement and  PR #2374 / Issue #2335 being closed, or am I missing something?

**Comment by terrylucas** [comment]
Please retry (there was a problem with publish of devtools_shared).

`flutter pub global activate devtools
`

Should see:

`Package devtools is currently active at version 0.9.3.
`

then 

`flutter pub global run devtools
`

**Comment by gustavogamino** [comment]
I was able to upgrade through `pub global`, but still didn't work. 

The Network page shows all http requests with `null` status code and there is no `Response` tab. Under `Headers` tab, response and request sections are empty too.

![DevTools 0 9 3 - Network Page Issue](https://user-images.githubusercontent.com/4420512/94937578-22365380-04a6-11eb-8080-2558c5107b4b.png)

**Comment by terrylucas** [comment]
Kenzie shouldn't this work?

**Comment by jameshp** [comment]
Hi can confirm, see the same issues as reported by @gustavogamino  
Could upgrade to 0.9.3 with the instructions above. But the following issues remain.
Response status is null,
Headers section Response and Request Headers are empty.

**Comment by kenzieschmoll** [comment]
Looks like the issue is that this commit https://github.com/dart-lang/sdk/commit/35680f0193656f9408384306a67524e65b5d85b5 didn't make it into Flutter 1.22, which contains Dart 2.10.0. The first tag that this commit is included in is 2.10.0-146.0.dev.

@jacob314 @devoncarew is it possible to loop someone in for a cherry pick?

**Comment by kenzieschmoll** [comment]
If you switch to the dev channel `flutter channel dev`, your problem should be fixed.

**Comment by devoncarew** [comment]
cc @csells; people will currently need to be on the dev channel to use this feature. We may want to consider a cherry-pick; given that this is not a crash / stability issue, I'm not sure it would qualify.

**Comment by csells** [comment]
I'd very much like to see this as a CP.

**Comment by gustavogamino** [comment]
@kenzieschmoll Indeed, changing to the dev channel fixed a few things.

Requests now get their status code and headers correctly, but for some reason the `Reponse` tab is not showing for most requests. Working proportion varies, but it's like 1 out of 5. That happens with the request, sometimes it shows, sometimes not. I did multiple recording sessions.

Not related, but I also got UI overflow exceptions on the `Overview` tab, apparently it doesn't have scroll like the others?

I'm currently running devtools `0.9.3+2`.

**Comment by kenzieschmoll** [comment]
If you look in the timeline, can you see HTTP response events attached to each HTTP request you are expecting to have a response for? If so, please click the "Export" button in the timeline and attach it to your response. That will help be debug what is happening in the Network tab if the Timeline shows responses but the Network profiler does not. Thanks.

**Comment by sunnykinger** [comment]
> I was able to upgrade through `pub global`, but still didn't work.
> 
> The Network page shows all http requests with `null` status code and there is no `Response` tab. Under `Headers` tab, response and request sections are empty too.
> 
> ![DevTools 0 9 3 - Network Page Issue](https://user-images.githubusercontent.com/4420512/94937578-22365380-04a6-11eb-8080-2558c5107b4b.png)

Facing exact same issue

**Comment by kenzieschmoll** [comment]
Please try the flutter dev branch, and the latest version of DevTools 0.9.3+4. `flutter pub global activate devtools` should pick up the latest version and if not, you can run `flutter pub global activate devtools 0.9.3+4`.

**Comment by jameshp** [comment]
running 0.9.3+4 with flutter in dev branch provides no "Response" tab in general. 
I got one call, where the empty array response [] is shown. 
Attached one export of my logs. As far as i can see the events section does not contain the response body
I see 

- connection established
- request initalized
- request body
- response received (But no body)

[dart_devtools_2020_10_8-1602167126086000.zip](https://github.com/flutter/devtools/files/5348579/dart_devtools_2020_10_8-1602167126086000.zip)

Here is also my flutter doctor info:

> pub global run fvm:main flutter doctor -v
FVM: Running version dev
[√] Flutter (Channel dev, 1.23.0-7.0.pre, on Microsoft Windows [Version 10.0.17763.1397], locale en-AT)
    • Flutter version 1.23.0-7.0.pre at C:\Users\polt\fvm\versions\dev
    • Framework revision db6e2d8aa5 (13 days ago), 2020-09-25 06:47:03 -0400
    • Engine revision 3a73d073c8
    • Dart version 2.11.0 (build 2.11.0-161.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\polt\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.49.3)
    • VS Code at C:\Users\polt\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Proxy Configuration
    • HTTP_PROXY is set
    • NO_PROXY is localhost,127.0.0.1,.kapschtraffic.com,.local,.kapsch.co.at,.lcl,.ktc-int.net,64.76.31.26
    • NO_PROXY contains 127.0.0.1
    • NO_PROXY contains localhost

[√] Connected device (5 available)
    • motorola one zoom (mobile) • ZY226LN466         • android-arm64  • Android 10 (API 29)
    • motorola one zoom (mobile) • 192.168.0.241:5555 • android-arm64  • Android 10 (API 29)
    • Web Server (web)           • web-server         • web-javascript • Flutter Tools
    • Chrome (web)               • chrome             • web-javascript • Google Chrome 86.0.4240.75
    • Edge (web)                 • edge               • web-javascript • Microsoft Edge 83.0.478.56

• No issues found!

**Comment by pixnbit** [comment]
> Please try the flutter dev branch, and the latest version of DevTools 0.9.3+4. `flutter pub global activate devtools` should pick up the latest version and if not, you can run `flutter pub global activate devtools 0.9.3+4`.

Thank you very much! I'm able to see the responses. It would be much more helpful if the text displayed can be selected. (for json pretty print formatting)

**Comment by softboy99** [comment]
after switch to flutter dev branch, the project cannot be compiled:
The named parameter 'child' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'child'.

**Comment by softboy99** [comment]
Wish this can be officailly released to next flutter stable version soon.

**Comment by softboy99** [comment]
After switch to flutter 1.22.1 stable version and DevTools 0.9.3+4,still doesn't work

**Comment by pixnbit** [comment]
> After switch to flutter 1.22.1 stable version and DevTools 0.9.3+4,still doesn't work

Very flaky, sometime the tab shows some times it doesn't. You can use Alice it's very easy to setup.

**Comment by leecommamichael** [comment]
I'm super excited to use this when it lands on Stable :)

**Comment by softboy99** [comment]
Hi
Has this been closed?

**Comment by sooxt98** [comment]
Still missing in v0.9.6
![image](https://user-images.githubusercontent.com/13378059/104256139-94f79780-54b5-11eb-8caa-f9228a9595c3.png)

**Comment by sunnykinger** [comment]
It's missing in v0.9.6. When can we expect it to be fixed?

**Comment by kenzieschmoll** [comment]
@sooxt98 could you please go to the Performance tab, simulate the activity in your app that sends the network requests, click "Refresh", and see if HTTP Response body events show up there? at that point if you click "Export" and attach the downloaded file to this issue, that would be very helpful for debugging the problem.

@bkonyi could we be dropping events on the vm side? I receive response body information for the sample apps I use, but maybe there are some cases we don't handle properly on the vm side?

**Comment by bkonyi** [comment]
Yeah, we definitely drop events (see https://github.com/flutter/devtools/issues/2480) and I bumped into it while working on my hackathon project, so I have a reproduction case. I'll take a look today.

**Comment by samuelematias** [comment]
I still have this issue. The DevTools on Network Tab, don't Show the HTTP status request and Response Body.

DevTools 0.9.6+3
Flutter 1.22.6 • channel stable

![dev-tools-response-body-dont-show](https://user-images.githubusercontent.com/5155386/106309855-788f8500-6241-11eb-85b6-16f89dedde1b.png)

**Comment by kenzieschmoll** [comment]
DevTools 0.9.7 will be released today and will contain the fix for this issue.

**Comment by samuelematias** [comment]
> DevTools 0.9.7 will be released today and will contain the fix for this issue.

Ok, thanks @kenzieschmoll !

**Comment by sunnykinger** [comment]
Now DevTools are not even running after the update.
![image](https://user-images.githubusercontent.com/6624048/106348186-4c7c0e80-62ea-11eb-86f4-d586e4b13148.png)

**Comment by samuelematias** [comment]
> Now DevTools are not even running after the update.


Yeah, the same issue here.

![Screen Shot 2021-01-30 at 12 18 57](https://user-images.githubusercontent.com/5155386/106360172-cb2a7900-62f5-11eb-9046-95850a0e2741.png)

**Comment by bkonyi** [comment]
@sunnykinger @samuelematias I've confirmed the issue you're seeing and filed #2649. There's a fix pending in https://github.com/flutter/devtools/pull/2650.

**Comment by sunnykinger** [comment]
> DevTools 0.9.7 will be released today and will contain the fix for this issue.

There was an issue with 0.9.7 (Unable to connect to VM Service), and now with 0.9.7+2, this issue seems to be resolved, but in the network tab, still no data in Request and Response Headers.

**Comment by sunnykinger** [comment]
0.9.7+3, no data in Request and Response Headers. All Empty.

**Comment by samuelematias** [comment]
> 0.9.7+3, no data in Request and Response Headers. All Empty.
> 
> @samuelematias Did it work for you?

The same problem here.
No Response Data, and. Status too.

And requests, only appear even with this problem, after a few attempts, it does not appear at first in the networking tab.

![Screen Shot 2021-02-09 at 08 02 37](https://user-images.githubusercontent.com/5155386/107355015-aaa8ae80-6aad-11eb-868b-a5c881a342ee.png)

**Comment by sunnykinger** [comment]
> > 0.9.7+3, no data in Request and Response Headers. All Empty.
> > @samuelematias Did it work for you?
> 
> The same problem here.
> No Response Data and Status too.
> 
> And requests, only appear even with this problem, after a few attempts, it does not appear at first in the networking tab.
> 
> ![Screen Shot 2021-02-09 at 08 02 37](https://user-images.githubusercontent.com/5155386/107355015-aaa8ae80-6aad-11eb-868b-a5c881a342ee.png)

yes same for me, it shows after a few attempts. I don't know what went wrong with it. I started development in Flutter like last year in May, everything was ok at that time.

**Comment by jlubeck** [comment]
I see Response tab and Response body on 0.9.7+3. But no Request body though.

I don't mean to sound rude (text can do that sometimes), but why is this issue closed when it looks like a lot of people are still having issues with this?

**Comment by sunnykinger** [comment]
@kenzieschmoll The issue is still there, why it has been closed?

**Comment by sooxt98** [comment]
This shouldn't be closed, is it because im using HttpClient which makes devtool confuse?
![image](https://user-images.githubusercontent.com/13378059/107603002-5d237180-6c66-11eb-9294-64e4bb96c572.png)

**Comment by bkonyi** [comment]
@kenzieschmoll, I've confirmed that this is still happening. It seems like we've still got some racey logic in the timeline processing. I'm working on writing proper network profiling RPCs in the Dart SDK so we don't need to deal with parsing this information from the timeline. That should resolve most of these headaches, but won't be available until at least the next beta release. We'll probably want to try and fix this issue in the meantime.

**Comment by bkonyi** [comment]
This should be resolved now that https://github.com/flutter/devtools/pull/2839 has been merged. This will require a Dart SDK update (likely `2.13.0`) for the fix to be available, even after a new DevTools version is released.

**Comment by softboy99** [comment]
waiting for flutter sdk update, 2.0.3 still use 2.12.0 dart sdk

**Comment by simplenotezy** [comment]
@bkonyi I am still facing this issue:

<img width="1723" alt="image" src="https://user-images.githubusercontent.com/3786627/231751461-79d531a2-4af6-44af-beca-14c20c73f6e8.png">

Using `Dart SDK version: 2.19.5`
And `DevTools version: 2.9.4`

I did this approach:

> Please retry (there was a problem with publish of devtools_shared).
> 
> `flutter pub global activate devtools `
> 
> Should see:
> 
> `Package devtools is currently active at version 0.9.3. `
> 
> then
> 
> `flutter pub global run devtools `

**Comment by bkonyi** [comment]
@simplenotezy that's a very old version of DevTools. I'd highly recommend upgrading to the latest stable SDK (and then upgrading to Dart 3.0 when it's released) as we've been regularly making improvements to the network tooling.

Also, `flutter pub global activate devtools` is no longer the proper way to use DevTools as we now ship DevTools as part of the Dart SDK. You'll want to open the DevTools URI output by `flutter run` or `dart run` instead.

**Comment by simplenotezy** [comment]
> @simplenotezy that's a very old version of DevTools. I'd highly recommend upgrading to the latest stable SDK (and then upgrading to Dart 3.0 when it's released) as we've been regularly making improvements to the network tooling.
> 
> Also, `flutter pub global activate devtools` is no longer the proper way to use DevTools as we now ship DevTools as part of the Dart SDK. You'll want to open the DevTools URI output by `flutter run` or `dart run` instead.

Interesting. I was under the belief that I was on some more recent version, as I just use brew to install flutter, and I recently upgraded flutter.

I was under the assumption that the DevTools came with Flutter.

Also I went here: https://github.com/flutter/devtools/releases to check versions - where do I find the latest version/changelog?

**Comment by bkonyi** [comment]
The release notes can be found here: https://docs.flutter.dev/development/tools/devtools/release-notes.

There's no way to update DevTools without updating your Flutter installation (or Dart SDK if you're just doing Dart development). Updating your Flutter installation will also update your Dart SDK used with Flutter.

**Comment by simplenotezy** [comment]
@bkonyi But I am already on the latest dart version:

```
❯ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.8, on macOS 13.3.1 22E261 darwin-arm64, locale en-DK)
[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3)
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.77.3)
[✓] Connected device (3 available)
[✓] HTTP Host Availability

• No issues found!

**Comment by simplenotezy** [comment]
@bkonyi If you have time could you help me understand why I have an old version of DevTools when I appear to be on the latest version of both flutter and dart? I use Brew to manage my flutter installation

**Comment by kenzieschmoll** [comment]
Can you paste the outputs of the following commands here?
1. `flutter --version`
2. `which flutter`
3. `which dart`
