### ISSUE TITLE
[Network] Request headers not captured

### ISSUE THREAD

**Issue by bleroux** [flutter/devtools#3343]
Request headers added by application code and by dart HttpClient are not captured by HttpProfiler

Steps to reproduce :

1 - Create an application that send a request :
```
    http.get(
      Uri.parse('http://localhost:8081'),
      headers: {
        'favorite-languages': 'dart,smalltalk,...',
      },
    ).then((response) {
```

2 - Open 'Network' tab on DevTools
3 - Let the application send the request
4 - Select the request and go to 'Headers' tab, displayed content is :

![Capture d’écran du 2021-09-04 18-27-21](https://user-images.githubusercontent.com/840911/132101666-93ea3476-6c62-435c-a194-f9cdacfd611b.png)

Despite the server receives following headers :
```
user-agent: Dart/2.15 (dart:io)
favorite-languages: dart,smalltalk,...
accept-encoding: gzip
host: localhost:8081
```

I created this issue to give more details on #3335 and #3283

**Comment by bleroux** [comment]
Related PR on Dart SDK has been merged (https://github.com/dart-lang/sdk/commit/ffe3ee691c45337a856ab4f685c52f914e1b63b1) 

Will soon land on Flutter master branch :crossed_fingers:

**Comment by bleroux** [comment]
Fix available on Flutter master branch :

![Capture d’écran du 2021-09-10 08-05-09](https://user-images.githubusercontent.com/840911/132807669-ff446467-c599-4f49-96cf-3c0d0c01aedd.png)

**Comment by Xrok** [comment]
I've updated to the last version (even on `dev` channel ) and still having the issue. Flutter DeTools only showing 
```
Request Headers:
content-length: [0]
```   
#### Request
```dart
final uri = Uri.parse('https://***.com/***');
final response = await http.get(uri, headers: {'Authorization': ***});
```
#### Versions
```bash
❯ flutter --version
Flutter 2.6.0-5.1.pre • channel dev • https://github.com/flutter/flutter.git
Framework • revision f2903d3da5 (10 days ago) • 2021-09-08 12:44:29 -0700
Engine • revision 0bd9be379a
Tools • Dart 2.15.0 (build 2.15.0-82.0.dev)
```

**Comment by bleroux** [comment]
@Xrok 
Your flutter version is from the 2021-09-08 12:44:29 -0700
The fix reaches master on the 10th of september.
You can switch to master channel or wait that it reaches dev channel
