### ISSUE TITLE
Cancelled requests are shown as "Pending"

### ISSUE THREAD

**Issue by ManuelRauber** [flutter/devtools#6642]
Hi,

I use the dio package to make HTTP requests to our API.

Dio provided a feature for canceling requests. Under the hood it uses [HttpClientRequest.abort](https://api.flutter.dev/flutter/dart-io/HttpClientRequest/abort.html) (see [here in dio's source](https://github.com/kuhnroyal/dio/blob/5076208444e2bd31129725328f32f9ec193135eb/dio/lib/src/adapters/io_adapter.dart#L110).

However, in DevTools it shows the request as Pending:

![image](https://github.com/flutter/devtools/assets/740791/ec6d9c90-e7d4-499b-ae5f-3d030d97fbf2)

It would be nice if it could show, that the request has been aborted. 
___
**DevTools version**: 2.25.0
**Connected Device**:
CPU / OS: arm64 (64 bit) ios
Dart Version: 3.1.3
Flutter Version: 3.13.7 / stable
Framework / Engine: 2f708eb839 / a794cf2681
Connected app type: Flutter native (debug build)

**Comment by kenzieschmoll** [comment]
We should see if we get an event for `abort()` calls and if we do, we should mark the request as cancelled in the UI. If we do not get an event, we should see if that is something we can add in dart-io

**Comment by CoderDake** [comment]
after doing some research it looks like the base functionality for cancelling a request does't exist.
Other packages build their own ways to accomplish this https://github.com/dart-lang/http/issues/424

**Comment by CoderDake** [comment]
I found the abort call that appears to be used for cancel: https://github.com/dart-lang/sdk/blob/f5fe3dddcc3401fb4848418f639a6f28187d63ce/sdk/lib/_http/http_impl.dart#L1604

I blindly tried adding `_profileData?.finishRequestWithError`to it, but wasn't able to get those events in devtools so this may require some more thought to figure out how to get the events to propagate

**Comment by kenzieschmoll** [comment]
This should be fixed by https://dart-review.googlesource.com/c/sdk/+/375800

**Comment by lewinpauli** [comment]
@kenzieschmoll Problem is still there 

Flutter Channel stable, 3.38.4 , Linux


[DartPad dio cancellable request](https://dartpad.dev/?id=e01631f4fe9521679c0b5442d1f41a5e)

if you copy the code into a flutter project and open the Dart Devtools Network Page you will see that cancelled request are still displayed as "Pending"

Wireshark is showing correct RST pakets

and chrome devtools are also showing correct cancelled status
